# Generated by Django 3.1.2 on 2020-11-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='listings',
            new_name='listing',
        ),
    ]
