# Generated by Django 3.1.2 on 2020-11-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20201103_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='listing_slug',
            field=models.CharField(default=models.CharField(max_length=200), max_length=200),
        ),
    ]
