# Generated by Django 3.1.2 on 2020-11-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_listing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='listing_slug',
            field=models.CharField(max_length=200),
        ),
    ]
